CREATE TABLE Students
(
	StudentID INT PRIMARY KEY NOT NULL,
	Name NVARCHAR(50) NOT NULL
)
INSERT INTO Students VALUES
(1,'Mila'),
(2,'Toni'),
(3,'Ron')

CREATE TABLE Exams
(
	ExamID INT PRIMARY KEY NOT NULL,
	Name NVARCHAR(50) NOT NULL
)

INSERT INTO Exams VALUES
(101,'SpringMVC'),
(102,'Neo4j'),
(103,'Oracle 11g')

CREATE TABLE StudentsExams
(
	StudentID INT REFERENCES Students(StudentID) NOT NULL,
	ExamID INT REFERENCES Exams(ExamID) NOT NULL
	PRIMARY KEY (StudentID, ExamID)
)
INSERT INTO StudentsExams VALUES
(1,101),
(1,102),
(2,101),
(3,103),
(2,102),
(2,103)


SELECT * FROM Students
SELECT * FROM Exams
SELECT * FROM StudentsExams